#!/bin/bash
# Generated by OpenDP - executed on the EC2 host by .github/workflows/deploy.yml
set -euo pipefail

DOMAIN="payment-processor.dev.opendp.delicatehug.com"
EXPECTED_IP="${EXPECTED_IP:-}"

# RACE GUARD 1: only one provisioning run at a time on this host
exec 9>/var/lock/opendp-provision.lock
echo "[provision] acquiring provisioning lock"
flock -w 600 9 || { echo "ERROR: another provisioning run holds the lock for >10min" >&2; exit 1; }

# RACE GUARD 2: wait for first-boot cloud-init (Terraform user_data runs dnf too)
echo "[provision] waiting for first-boot cloud-init to finish"
for i in $(seq 1 60); do
  [ -f /var/lib/cloud/instance/boot-finished ] && break
  echo "[provision] cloud-init still running (check $i/60)"; sleep 5
done

# RACE GUARD 3: retry dnf while another package transaction holds the lock / cache is being rewritten
dnf_retry() {
  for attempt in 1 2 3 4 5 6; do
    if dnf "$@"; then return 0; fi
    echo "dnf attempt $attempt failed; cleaning cache and retrying" >&2
    dnf clean packages >/dev/null 2>&1 || true
    sleep 10
  done
  echo "dnf $* failed after retries" >&2
  return 1
}

# RACE GUARD 4: Let's Encrypt validates from the public internet, so the public DNS answer
# must already point at this host before certbot runs
wait_for_public_dns() {
  for attempt in $(seq 1 40); do
    answer=$(curl -fsS -H 'accept: application/dns-json' "https://cloudflare-dns.com/dns-query?name=$DOMAIN&type=A" || true)
    if [ -n "$EXPECTED_IP" ] && echo "$answer" | grep -q "$EXPECTED_IP"; then
      echo "Public DNS for $DOMAIN resolves to $EXPECTED_IP"
      return 0
    fi
    echo "Waiting for public DNS $DOMAIN -> $EXPECTED_IP (attempt $attempt/40)" >&2
    sleep 15
  done
  echo "ERROR: public DNS for $DOMAIN never resolved to $EXPECTED_IP" >&2
  return 1
}

dnf_retry install -y nodejs npm nginx git augeas-libs
cd /opt/app && sudo -u ec2-user npm install --omit=dev

cat > /etc/systemd/system/app.service <<'UNEOF'
[Unit]
Description=payment-processor application service
After=network.target

[Service]
Type=simple
User=ec2-user
WorkingDirectory=/opt/app
Environment=PORT=3000
ExecStart=/usr/bin/node /opt/app/src/index.js
Restart=always

[Install]
WantedBy=multi-user.target
UNEOF

# HTTP vhost; certbot extends it with the 443 server block and HTTP->HTTPS redirect
rm -f /etc/nginx/conf.d/default.conf
cat > /etc/nginx/conf.d/payment-processor.conf <<'NGINXEOF'
server {
    listen 80;
    listen [::]:80;
    server_name payment-processor.dev.opendp.delicatehug.com;
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
NGINXEOF

systemctl daemon-reload
systemctl enable app.service
systemctl restart app.service
systemctl enable nginx
systemctl restart nginx

# Publicly trusted TLS certificate via Let's Encrypt (HTTP-01 on port 80)
if [ ! -x /opt/certbot/bin/certbot ]; then
  python3 -m venv /opt/certbot
  /opt/certbot/bin/pip install --upgrade pip
  /opt/certbot/bin/pip install certbot certbot-nginx
fi
ln -sf /opt/certbot/bin/certbot /usr/local/bin/certbot
echo "[provision] waiting for public DNS then requesting certificate"
wait_for_public_dns
certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos --register-unsafely-without-email --redirect
cat > /etc/systemd/system/certbot-renew.service <<'RSEOF'
[Unit]
Description=Renew Let's Encrypt certificates

[Service]
Type=oneshot
ExecStart=/usr/local/bin/certbot renew --quiet --deploy-hook 'systemctl reload nginx'
RSEOF
cat > /etc/systemd/system/certbot-renew.timer <<'RTEOF'
[Unit]
Description=Twice-daily Let's Encrypt renewal check

[Timer]
OnCalendar=*-*-* 03,15:00:00
RandomizedDelaySec=1h
Persistent=true

[Install]
WantedBy=timers.target
RTEOF
systemctl daemon-reload
systemctl enable --now certbot-renew.timer

systemctl reload nginx
